version: '3.1'

services:
  database:
    image: mysql:8.2.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    restart: always

  editor:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: hydra
    restart: always
